version: '3.1'
services:
  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stats

  stats-db:
    image: postgres:15-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=straga
      - POSTGRES_PASSWORD=iamroot
